const SHOW_UPCOMING = "SHOW_UPCOMING";
const SHOW_DETAIL = "SHOW_DETAIL";
const CANCEL_BOOKING = "CANCEL_BOOKING";
const ADD_NOTES = "ADD_NOTES";
const CONTACT_PRO = "CONTACT_PRO";

export { SHOW_DETAIL, SHOW_UPCOMING, ADD_NOTES, CANCEL_BOOKING, CONTACT_PRO };
