export const productsConstants = {
	RECEIVE_PRODUCTS : 'RECEIVE_PRODUCTS',
	ADD_TO_CART : 'ADD_TO_CART',
	SET_CHECKOUT_STATUS : 'SET_CHECKOUT_STATUS',
    SET_ITEMS : 'SET_ITEMS',
	ADD_COUNT : 'ADD_COUNT',
	DEL_PRODUCT : 'DEL_PRODUCT',
	DEC_PRODUCT : 'DEC_PRODUCT',
	DEL_COUNT : 'DEL_COUNT',
	CLEAR_PRODUCT : 'CLEAR_PRODUCT',
	ADD_HISTORY : 'ADD_HISTORY',
};

